modLoader="javafml"
loaderVersion="${loader_version_range}"
license="All Rights Reserved"

[[mods]]
modId="create_chocolate"
version="${mod_version}"
displayName="Create More Chocolate"
authors="DrEnough"
description='''Addon for mod Create, adding food like chocolate'''
[[dependencies.create_chocolate]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.create_chocolate]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"
[[dependencies.create_chocolate]]
modId="create"
mandatory=true
versionRange="[0.5.1.f,)"
ordering="NONE"
side="BOTH"
[[dependencies.create_chocolate]]
modId="jei"
mandatory=false
versionRange="[15.3.0.4,)"
ordering="NONE"
side="BOTH"