modLoader="javafml"
loaderVersion="${loader_version_range}"
license="All Rights Reserved"

[[mods]]
modId="create_chocolate"
version="${mod_version}"
displayName="Create More Chocolate"
authors="DrEnough"
description='''Addon for mod Create, adding food like chocolate'''

[[dependencies.create_chocolate]]
modId="neoforge"
type="required"
versionRange="[21.1.152,)"
ordering="NONE"
side="BOTH"

[[dependencies.create_chocolate]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.create_chocolate]]
modId="jei"
type="optional"
versionRange="[19.21.0.247,)"  # Updated to the correct JEI version range
ordering="NONE"
side="BOTH"

[[dependencies.create_chocolate]]
modId="create"
type="required"
versionRange="[6.0.6,6.1.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.create_chocolate]]
modId="ponder"
type="required"
versionRange="[1.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.create_chocolate]]
modId="flywheel"
type="required"
versionRange="[1.0.4,)"
ordering="AFTER"
side="CLIENT"